# .github/workflows/build.yml

name: Build Design Tokens

on:
  push:
    paths:
      - 'tokens/token-test.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Normalize tokens
        run: node normalize-token.js

      - name: Build design tokens
        run: npm run build:tokens

      - name: Upload CSS/SCSS result
        uses: actions/upload-artifact@v3
        with:
          name: design-tokens-output
          path: build/
